name: Tests CI
<<<<<<< HEAD

on:
  push:
  pull_request:

=======
on: [push, pull_request]
>>>>>>> Add unit test github action
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        uses: actions/setup-node@v1
        with:
<<<<<<< HEAD
          node-version: "16"
      - run: yarn install
      - run: yarn test
=======
          node-version: '16'
      - run: yarn install
      - run: npx hardhat test


>>>>>>> Add unit test github action
